create-pool:
	./scripts/create_pool.sh

show-pool:
	furynd q clp pool ceth

show-params:
	furynd q clp params

remove-liquidity:
	./scripts/remove_liquidity.sh

show-lp:
	./scripts/show_lp.sh

unlock-liquidity:
	./scripts/unlock_liquidity.sh
	
submit-proposal:
	./scripts/submit_proposal.sh

view-proposal:
	furynd q gov proposal 1

vote:
	./scripts/vote.sh