version: '3'

services:
  furynode0:
    image: furynet/furynode:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: furynode0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR0}
    volumes:
      - ./furynode/root/scripts:/root/scripts:Z
    command: /root/scripts/furynode.sh
    networks:
      furynet:
        ipv4_address: ${IPADDR0}

  furynode1:
    image: furynet/furynode:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: furynode1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR1}
    volumes:
      - ./furynode/root/scripts:/root/scripts:Z
    command: /root/scripts/furynode.sh
    networks:
      furynet:
        ipv4_address: ${IPADDR1}

  ts-relayer:
    image: furynet/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      FURYNODE0_MNEMONIC: ${MNEMONIC}
      FURYNODE1_MNEMONIC: ${MNEMONIC}
      RPC0: ${IPADDR0}:26657
      RPC1: ${IPADDR1}:26657
      PREFIX0: fury
      PREFIX1: fury
      GAS_PRICE0: "0.5fury"
      GAS_PRICE1: "0.5fury"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - furynode0
      - furynode1
    command: /root/scripts/ts-relayer.sh
    networks:
      furynet:
        ipv4_address: ${IPADDR2}

networks:
  furynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
